# Previo

In [8]:
import pandas as pd
import os

#Ruta directorio principal
ROOT_DIR = os.path.abspath(os.path.join(os.getcwd(), "..", ".."))
#Ruta Bases de datos
BRONZE = os.path.abspath(os.path.join(ROOT_DIR, "Datasets", "Bronze"))
SILVER = os.path.abspath(os.path.join(ROOT_DIR, "Datasets", "Silver"))
GOLD = os.path.abspath(os.path.join(ROOT_DIR, "Datasets", "Gold"))

#Fecha del fichero
ano = 2025
mes = 11

#Ficheros
yellow = f"yellow_tripdata_{ano}-{mes:02d}.parquet"
green  = f"green_tripdata_{ano}-{mes:02d}.parquet"
fhv    = f"fhv_tripdata_{ano}-{mes:02d}.parquet"
fhvhv  = f"fhvhv_tripdata_{ano}-{mes:02d}.parquet"

# Yellow

In [ ]:
Yellow  = pd.read_parquet(BRONZE + "/" + yellow)
Yellow

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee,cbd_congestion_fee
0,7,2025-11-01 00:13:25,2025-11-01 00:13:25,1.0,1.68,1.0,N,43,186,1,14.90,0.00,0.5,1.50,0.00,1.0,22.15,2.5,0.00,0.75
1,2,2025-11-01 00:49:07,2025-11-01 01:01:22,1.0,2.28,1.0,N,142,237,1,14.20,1.00,0.5,4.99,0.00,1.0,24.94,2.5,0.00,0.75
2,1,2025-11-01 00:07:19,2025-11-01 00:20:41,0.0,2.70,1.0,N,163,238,1,15.60,4.25,0.5,4.27,0.00,1.0,25.62,2.5,0.00,0.75
3,2,2025-11-01 00:00:00,2025-11-01 01:01:03,3.0,12.87,1.0,N,138,261,1,66.70,6.00,0.5,0.00,6.94,1.0,86.14,2.5,1.75,0.75
4,1,2025-11-01 00:18:50,2025-11-01 00:49:32,0.0,8.40,1.0,N,138,37,2,39.40,7.75,0.5,0.00,0.00,1.0,48.65,0.0,1.75,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4181439,2,2025-11-30 23:12:44,2025-11-30 23:43:26,NaN,10.62,NaN,None,68,169,0,33.16,0.00,0.5,0.00,6.94,1.0,44.85,NaN,NaN,0.75
4181440,1,2025-11-30 23:10:35,2025-11-30 23:28:24,NaN,6.50,NaN,None,48,116,0,22.17,0.00,0.5,0.00,0.00,1.0,26.92,NaN,NaN,0.75
4181441,2,2025-11-30 23:09:43,2025-11-30 23:36:08,NaN,8.10,NaN,None,145,152,0,-4.75,0.00,0.5,0.00,0.00,1.0,4.06,NaN,NaN,0.75
4181442,1,2025-11-30 23:29:41,2025-11-30 23:47:09,NaN,5.60,NaN,None,116,48,0,21.42,0.00,0.5,0.00,0.00,1.0,26.17,NaN,NaN,0.75
4181443,2,2025-11-30 23:59:06,2025-12-01 00:12:18,NaN,3.22,NaN,None,144,230,0,35.87,0.00,0.5,0.00,0.00,1.0,40.62,NaN,NaN,0.75

In [18]:
print(Yellow.columns)

Index(['VendorID', 'tpep_pickup_datetime', 'tpep_dropoff_datetime',
       'passenger_count', 'trip_distance', 'RatecodeID', 'store_and_fwd_flag',
       'PULocationID', 'DOLocationID', 'payment_type', 'fare_amount', 'extra',
       'mta_tax', 'tip_amount', 'tolls_amount', 'improvement_surcharge',
       'total_amount', 'congestion_surcharge', 'Airport_fee',
       'cbd_congestion_fee'],
      dtype='object')

In [19]:
Yellow.head()

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee,cbd_congestion_fee
0,7,2025-11-01 00:13:25,2025-11-01 00:13:25,1.0,1.68,1.0,N,43,186,1,14.9,0.00,0.5,1.50,0.00,1.0,22.15,2.5,0.00,0.75
1,2,2025-11-01 00:49:07,2025-11-01 01:01:22,1.0,2.28,1.0,N,142,237,1,14.2,1.00,0.5,4.99,0.00,1.0,24.94,2.5,0.00,0.75
2,1,2025-11-01 00:07:19,2025-11-01 00:20:41,0.0,2.70,1.0,N,163,238,1,15.6,4.25,0.5,4.27,0.00,1.0,25.62,2.5,0.00,0.75
3,2,2025-11-01 00:00:00,2025-11-01 01:01:03,3.0,12.87,1.0,N,138,261,1,66.7,6.00,0.5,0.00,6.94,1.0,86.14,2.5,1.75,0.75
4,1,2025-11-01 00:18:50,2025-11-01 00:49:32,0.0,8.40,1.0,N,138,37,2,39.4,7.75,0.5,0.00,0.00,1.0,48.65,0.0,1.75,0.00

In [20]:
Yellow.describe()

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee,cbd_congestion_fee
count,4.181444e+06,4181444,4181444,3.166704e+06,4.181444e+06,3.166704e+06,4.181444e+06,4.181444e+06,4.181444e+06,4.181444e+06,4.181444e+06,4.181444e+06,4.181444e+06,4.181444e+06,4.181444e+06,4.181444e+06,3.166704e+06,3.166704e+06,4.181444e+06
mean,1.879423e+00,2025-11-15 10:46:58.380461824,2025-11-15 11:05:20.075879168,1.287101e+00,6.530914e+00,4.464459e+00,1.620342e+02,1.615968e+02,9.050739e-01,1.711793e+01,1.059649e+00,4.818083e-01,2.862241e+00,5.179058e-01,9.498621e-01,2.561495e+01,2.185029e+00,1.430022e-01,5.350028e-01
min,1.000000e+00,2008-12-31 23:04:21,2008-12-31 23:32:25,0.000000e+00,0.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,0.000000e+00,-1.508700e+03,-8.500000e+00,-5.000000e-01,-3.333300e+02,-1.150500e+02,-1.000000e+00,-1.514450e+03,-2.500000e+00,-1.750000e+00,-7.500000e-01
25%,2.000000e+00,2025-11-08 00:02:02.750000128,2025-11-08 00:17:31.750000128,1.000000e+00,1.050000e+00,1.000000e+00,1.140000e+02,1.070000e+02,1.000000e+00,7.900000e+00,0.000000e+00,5.000000e-01,0.000000e+00,0.000000e+00,1.000000e+00,1.435000e+01,2.500000e+00,0.000000e+00,0.000000e+00
50%,2.000000e+00,2025-11-15 10:54:55,2025-11-15 11:08:58.500000,1.000000e+00,1.890000e+00,1.000000e+00,1.610000e+02,1.620000e+02,1.000000e+00,1.280000e+01,0.000000e+00,5.000000e-01,2.000000e+00,0.000000e+00,1.000000e+00,2.058000e+01,2.500000e+00,0.000000e+00,7.500000e-01
75%,2.000000e+00,2025-11-22 11:27:26.249999872,2025-11-22 11:42:58.249999872,1.000000e+00,3.840000e+00,1.000000e+00,2.330000e+02,2.340000e+02,1.000000e+00,2.190000e+01,2.500000e+00,5.000000e-01,4.000000e+00,0.000000e+00,1.000000e+00,3.005000e+01,2.500000e+00,0.000000e+00,7.500000e-01
max,7.000000e+00,2025-11-30 23:59:59,2025-12-01 21:41:00,8.000000e+00,2.560676e+05,9.900000e+01,2.650000e+02,2.650000e+02,4.000000e+00,1.508700e+03,1.500000e+01,1.050000e+01,5.750000e+02,3.000000e+02,2.500000e+00,1.514450e+03,2.500000e+00,6.750000e+00,7.500000e-01
std,7.463690e-01,NaN,NaN,7.043416e-01,6.274616e+02,1.782839e+01,6.633875e+01,7.054632e+01,6.988073e-01,1.957928e+01,1.736080e+00,1.200647e-01,4.002382e+00,2.140548e+00,2.656246e-01,2.377465e+01,9.159368e-01,5.190179e-01,3.516708e-01

In [ ]:
#Nulos
(Yellow.isna().mean() * 100).sort_values(ascending=False)

0

In [ ]:
#duplicados
Yellow.duplicated().sum()

# Green

In [15]:
Green  = pd.read_parquet(BRONZE + "/" + green)
Green

,VendorID,lpep_pickup_datetime,lpep_dropoff_datetime,store_and_fwd_flag,RatecodeID,PULocationID,DOLocationID,passenger_count,trip_distance,fare_amount,...,mta_tax,tip_amount,tolls_amount,ehail_fee,improvement_surcharge,total_amount,payment_type,trip_type,congestion_surcharge,cbd_congestion_fee
0,2,2025-11-01 00:34:48,2025-11-01 00:41:39,N,1.0,74,42,1.0,0.74,7.20,...,0.5,1.94,0.0,NaN,1.0,11.64,1.0,1.0,0.00,0.00
1,2,2025-11-01 00:18:52,2025-11-01 00:24:27,N,1.0,74,42,2.0,0.95,7.20,...,0.5,0.00,0.0,NaN,1.0,9.70,2.0,1.0,0.00,0.00
2,2,2025-11-01 01:03:14,2025-11-01 01:15:24,N,1.0,83,160,1.0,2.19,13.50,...,0.5,5.00,0.0,NaN,1.0,21.00,1.0,1.0,0.00,0.00
3,2,2025-11-01 00:10:57,2025-11-01 00:24:53,N,1.0,166,127,1.0,5.44,24.70,...,0.5,0.50,0.0,NaN,1.0,27.70,1.0,1.0,0.00,0.00
4,1,2025-11-01 00:03:48,2025-11-01 00:19:38,N,1.0,166,262,1.0,3.20,18.40,...,1.5,1.00,0.0,NaN,1.0,24.65,1.0,1.0,2.75,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46907,2,2025-11-30 19:58:34,2025-11-30 20:14:28,None,NaN,59,51,NaN,8.50,33.22,...,0.5,0.00,0.0,NaN,1.0,34.72,NaN,NaN,NaN,0.00
46908,2,2025-11-30 19:34:00,2025-11-30 19:46:00,None,NaN,74,151,NaN,1.73,13.86,...,0.5,0.77,0.0,NaN,1.0,16.13,NaN,NaN,NaN,0.00
46909,2,2025-11-30 21:46:46,2025-11-30 22:17:55,None,NaN,33,163,NaN,7.52,38.42,...,0.5,1.00,0.0,NaN,1.0,44.42,NaN,NaN,NaN,0.75
46910,2,2025-11-30 21:00:00,2025-11-30 21:15:00,None,NaN,16,95,NaN,5.61,24.67,...,0.5,0.00,0.0,NaN,1.0,26.17,NaN,NaN,NaN,0.00
46911,2,2025-11-30 23:26:00,2025-11-30 23:42:00,None,NaN,65,87,NaN,2.91,14.46,...,0.5,3.89,0.0,NaN,1.0,23.35,NaN,NaN,NaN,0.75

# FVH

In [16]:
FHV  = pd.read_parquet(BRONZE + "/" + fhv)
FHV

FileNotFoundError: [Errno 2] No such file or directory: 'c:\\Users\\carlo\\Documents\\TFM\\Datasets\\Bronze/fhv_tripdata_2025-11.parquet'

# FVHVH

In [17]:
FHVHV  = pd.read_parquet(BRONZE + "/" + fhvhv)
FHVHV

,hvfhs_license_num,dispatching_base_num,originating_base_num,request_datetime,on_scene_datetime,pickup_datetime,dropoff_datetime,PULocationID,DOLocationID,trip_miles,...,congestion_surcharge,airport_fee,tips,driver_pay,shared_request_flag,shared_match_flag,access_a_ride_flag,wav_request_flag,wav_match_flag,cbd_congestion_fee
0,HV0003,B03404,B03404,2025-11-01 00:31:47,2025-11-01 00:36:39,2025-11-01 00:41:10,2025-11-01 00:59:52,148,170,3.480,...,2.75,0.0,0.0,46.10,N,N,N,N,N,1.5
1,HV0003,B03404,B03404,2025-11-01 00:10:11,2025-11-01 00:15:19,2025-11-01 00:17:14,2025-11-01 00:47:29,72,228,6.640,...,0.00,0.0,0.0,37.43,N,N,N,N,N,0.0
2,HV0003,B03404,B03404,2025-11-01 00:32:49,2025-11-01 00:38:38,2025-11-01 00:40:39,2025-11-01 01:04:02,137,143,3.510,...,2.75,0.0,0.0,39.16,N,N,N,N,N,1.5
3,HV0003,B03404,B03404,2025-11-01 00:09:56,2025-11-01 00:17:21,2025-11-01 00:18:34,2025-11-01 00:36:06,112,140,4.150,...,2.75,0.0,0.0,34.70,N,N,N,N,N,0.0
4,HV0003,B03404,B03404,2025-11-01 00:38:04,2025-11-01 00:41:53,2025-11-01 00:42:13,2025-11-01 01:15:07,141,82,5.510,...,2.75,0.0,0.0,30.78,N,N,N,N,N,1.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20818235,HV0003,B03404,B03404,2025-11-30 23:43:40,2025-11-30 23:45:35,2025-11-30 23:45:51,2025-11-30 23:55:10,47,169,1.320,...,0.00,0.0,0.0,7.78,N,N,N,N,N,0.0
20818236,HV0005,B03406,None,2025-11-30 22:54:45,2025-11-30 22:59:43,2025-11-30 23:00:43,2025-11-30 23:20:09,185,159,9.428,...,0.00,0.0,0.0,24.57,N,N,N,N,N,0.0
20818237,HV0005,B03406,None,2025-11-30 23:26:22,2025-11-30 23:28:56,2025-11-30 23:29:00,2025-11-30 23:39:33,159,47,2.188,...,0.00,0.0,0.0,9.69,N,N,N,N,N,0.0
20818238,HV0003,B03404,B03404,2025-11-30 23:39:54,2025-11-30 23:50:27,2025-11-30 23:50:27,2025-12-01 00:14:49,132,157,13.080,...,0.00,2.5,3.0,46.14,N,N,N,N,N,0.0
20818239,HV0003,B03404,B03404,2025-11-30 23:41:28,2025-11-30 23:41:49,2025-11-30 23:43:43,2025-11-30 23:48:23,249,246,1.280,...,2.75,0.0,0.0,4.67,N,N,N,N,N,1.5

# PCA